// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace RoslynCodeGenTest.Models
{
    public partial class Field
    {
        [Key]
        public Guid Id { get; set; }
        public Guid TableId { get; set; }
        [Required]
        public string FieldName { get; set; }
        [Required]
        public string FieldDataType { get; set; }
        public string FieldProperties { get; set; }
        [Column("fieldOrder")]
        public int FieldOrder { get; set; }

        [ForeignKey(nameof(TableId))]
        [InverseProperty("Fields")]
        public virtual Table Table { get; set; }
    }
}